services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres_data: